// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using Microsoft.ML.Probabilistic;
using Microsoft.ML.Probabilistic.Distributions;
using Microsoft.ML.Probabilistic.Factors;
using Microsoft.ML.Probabilistic.Collections;

namespace Models
{
	/// <summary>
	/// Generated algorithm for performing inference.
	/// </summary>
	/// <remarks>
	/// If you wish to use this class directly, you must perform the following steps:
	/// 1) Create an instance of the class.
	/// 2) Set the value of any externally-set fields e.g. data, priors.
	/// 3) Call the Execute(numberOfIterations) method.
	/// 4) Use the XXXMarginal() methods to retrieve posterior marginals for different variables.
	/// 
	/// Generated by Infer.NET 0.4.2203.202 at 15:23 on giovedì 14 luglio 2022.
	/// </remarks>
	public partial class Model90_EP : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>True if Changed_matchTime has executed. Set this to false to force re-execution of Changed_matchTime</summary>
		public bool Changed_matchTime_isDone;
		/// <summary>True if Changed_matchTime_numberOfIterations_PlayerIndex_PlayerInTeam_playerTime_vdouble__800 has executed. Set this to false to force re-execution of Changed_matchTime_numberOfIterations_PlayerIndex_PlayerInTeam_playerTime_vdouble__800</summary>
		public bool Changed_matchTime_numberOfIterations_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isDone;
		/// <summary>True if Changed_numberOfIterations_PlayerIndex_PlayerInTeam_time_passed_vdouble__800_vdouble__801_vint__212 has executed. Set this to false to force re-execution of Changed_numberOfIterations_PlayerIndex_PlayerInTeam_time_passed_vdouble__800_vdouble__801_vint__212</summary>
		public bool Changed_numberOfIterations_PlayerIndex_PlayerInTeam_time_passed_vdouble__800_vdouble__801_vint__212_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_Init_matchTime_PlayerIndex_PlayerInTeam_playerTime_vdouble__800 has executed. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_Init_matchTime_PlayerIndex_PlayerInTeam_playerTime_vdouble__800</summary>
		public bool Changed_numberOfIterationsDecreased_Init_matchTime_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_Init_matchTime_PlayerIndex_PlayerInTeam_playerTime_vdouble__800 has performed initialisation. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_Init_matchTime_PlayerIndex_PlayerInTeam_playerTime_vdouble__800</summary>
		public bool Changed_numberOfIterationsDecreased_Init_matchTime_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isInitialised;
		/// <summary>True if Changed_numberOfIterationsDecreased_PlayerIndex_PlayerInTeam_vint__212_Init_time_passed_vdouble__8005 has executed. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_PlayerIndex_PlayerInTeam_vint__212_Init_time_passed_vdouble__8005</summary>
		public bool Changed_numberOfIterationsDecreased_PlayerIndex_PlayerInTeam_vint__212_Init_time_passed_vdouble__8005_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_PlayerIndex_PlayerInTeam_vint__212_Init_time_passed_vdouble__8005 has performed initialisation. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_PlayerIndex_PlayerInTeam_vint__212_Init_time_passed_vdouble__8005</summary>
		public bool Changed_numberOfIterationsDecreased_PlayerIndex_PlayerInTeam_vint__212_Init_time_passed_vdouble__8005_isInitialised;
		/// <summary>True if Changed_PlayerIndex has executed. Set this to false to force re-execution of Changed_PlayerIndex</summary>
		public bool Changed_PlayerIndex_isDone;
		/// <summary>True if Changed_PlayerIndex_PlayerInTeam_vint__212 has executed. Set this to false to force re-execution of Changed_PlayerIndex_PlayerInTeam_vint__212</summary>
		public bool Changed_PlayerIndex_PlayerInTeam_vint__212_isDone;
		/// <summary>True if Changed_PlayerInTeam has executed. Set this to false to force re-execution of Changed_PlayerInTeam</summary>
		public bool Changed_PlayerInTeam_isDone;
		/// <summary>True if Changed_PlayerInTeam_playerTime has executed. Set this to false to force re-execution of Changed_PlayerInTeam_playerTime</summary>
		public bool Changed_PlayerInTeam_playerTime_isDone;
		/// <summary>True if Changed_PlayerInTeam_time_passed has executed. Set this to false to force re-execution of Changed_PlayerInTeam_time_passed</summary>
		public bool Changed_PlayerInTeam_time_passed_isDone;
		/// <summary>True if Changed_vdouble__800 has executed. Set this to false to force re-execution of Changed_vdouble__800</summary>
		public bool Changed_vdouble__800_isDone;
		/// <summary>True if Changed_vdouble__801 has executed. Set this to false to force re-execution of Changed_vdouble__801</summary>
		public bool Changed_vdouble__801_isDone;
		/// <summary>True if Changed_vint__212 has executed. Set this to false to force re-execution of Changed_vint__212</summary>
		public bool Changed_vint__212_isDone;
		/// <summary>True if Constant has executed. Set this to false to force re-execution of Constant</summary>
		public bool Constant_isDone;
		/// <summary>Field backing the matchTime property</summary>
		private double[] MatchTime;
		/// <summary>Message to marginal of 'matchTime'</summary>
		public DistributionStructArray<Gaussian,double> matchTime_marginal_F;
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		/// <summary>Field backing the PlayerIndex property</summary>
		private int[][][] playerIndex;
		/// <summary>Message to marginal of 'PlayerIndex'</summary>
		public PointMass<int[][][]> PlayerIndex_marginal_F;
		/// <summary>Field backing the PlayerInTeam property</summary>
		private int[][] playerInTeam;
		/// <summary>Message to marginal of 'PlayerInTeam'</summary>
		public PointMass<int[][]> PlayerInTeam_marginal_F;
		/// <summary>Field backing the playerTime property</summary>
		private double[][][] PlayerTime;
		/// <summary>Message to marginal of 'playerTime'</summary>
		public DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]> playerTime_marginal_F;
		/// <summary>Field backing the time_passed property</summary>
		private double[][][] Time_passed;
		/// <summary>Message to marginal of 'time_passed'</summary>
		public DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]> time_passed_marginal_F;
		/// <summary>Field backing the vdouble__800 property</summary>
		private double[] Vdouble__800;
		/// <summary>Message to marginal of 'vdouble__800'</summary>
		public DistributionStructArray<Gaussian,double> vdouble__800_marginal_F;
		/// <summary>Field backing the vdouble__801 property</summary>
		private double[] Vdouble__801;
		/// <summary>Message to marginal of 'vdouble__801'</summary>
		public DistributionStructArray<Gaussian,double> vdouble__801_marginal_F;
		/// <summary>Message to marginal of 'vdouble__802'</summary>
		public DistributionStructArray<Gaussian,double> vdouble__802_marginal_F;
		/// <summary>Buffer for VariablePointOp_Rprop.MarginalAverageConditional</summary>
		public RpropBufferData[] vdouble__802_use_B_nMatches__buffer;
		/// <summary>Message to marginal of 'vdouble__809'</summary>
		public DistributionStructArray<Gaussian,double> vdouble__809_marginal_F;
		public Gaussian[][][] vdouble__809_PlayerIndex_nMatches_nTeamsPerMatch_nPlayersMinusPerTeam_1__B;
		/// <summary>Field backing the vint__212 property</summary>
		private int[] Vint__212;
		/// <summary>Message to marginal of 'vint__212'</summary>
		public PointMass<int[]> vint__212_marginal_F;
		#endregion

		#region Properties
		/// <summary>The externally-specified value of 'matchTime'</summary>
		public double[] matchTime
		{
			get {
				return this.MatchTime;
			}
			set {
				if ((value!=null)&&(value.Length!=1000)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+1000)+" was expected for variable \'matchTime\'");
				}
				this.MatchTime = value;
				this.numberOfIterationsDone = 0;
				this.Changed_matchTime_isDone = false;
				this.Changed_numberOfIterationsDecreased_Init_matchTime_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isInitialised = false;
				this.Changed_matchTime_numberOfIterations_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isDone = false;
			}
		}

		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		/// <summary>The externally-specified value of 'PlayerIndex'</summary>
		public int[][][] PlayerIndex
		{
			get {
				return this.playerIndex;
			}
			set {
				if ((value!=null)&&(value.Length!=1000)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+1000)+" was expected for variable \'PlayerIndex\'");
				}
				this.playerIndex = value;
				this.numberOfIterationsDone = 0;
				this.Changed_PlayerIndex_isDone = false;
				this.Changed_PlayerIndex_PlayerInTeam_vint__212_isDone = false;
				this.Changed_numberOfIterationsDecreased_PlayerIndex_PlayerInTeam_vint__212_Init_time_passed_vdouble__8005_isDone = false;
				this.Changed_numberOfIterations_PlayerIndex_PlayerInTeam_time_passed_vdouble__800_vdouble__801_vint__212_isDone = false;
				this.Changed_numberOfIterationsDecreased_Init_matchTime_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isInitialised = false;
				this.Changed_matchTime_numberOfIterations_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'PlayerInTeam'</summary>
		public int[][] PlayerInTeam
		{
			get {
				return this.playerInTeam;
			}
			set {
				if ((value!=null)&&(value.Length!=1000)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+1000)+" was expected for variable \'PlayerInTeam\'");
				}
				this.playerInTeam = value;
				this.numberOfIterationsDone = 0;
				this.Changed_PlayerInTeam_time_passed_isDone = false;
				this.Changed_PlayerInTeam_playerTime_isDone = false;
				this.Changed_PlayerInTeam_isDone = false;
				this.Changed_PlayerIndex_PlayerInTeam_vint__212_isDone = false;
				this.Changed_numberOfIterationsDecreased_PlayerIndex_PlayerInTeam_vint__212_Init_time_passed_vdouble__8005_isDone = false;
				this.Changed_numberOfIterations_PlayerIndex_PlayerInTeam_time_passed_vdouble__800_vdouble__801_vint__212_isDone = false;
				this.Changed_numberOfIterationsDecreased_Init_matchTime_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isInitialised = false;
				this.Changed_matchTime_numberOfIterations_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'playerTime'</summary>
		public double[][][] playerTime
		{
			get {
				return this.PlayerTime;
			}
			set {
				if ((value!=null)&&(value.Length!=1000)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+1000)+" was expected for variable \'playerTime\'");
				}
				this.PlayerTime = value;
				this.numberOfIterationsDone = 0;
				this.Changed_PlayerInTeam_playerTime_isDone = false;
				this.Changed_numberOfIterationsDecreased_Init_matchTime_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isInitialised = false;
				this.Changed_matchTime_numberOfIterations_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'time_passed'</summary>
		public double[][][] time_passed
		{
			get {
				return this.Time_passed;
			}
			set {
				if ((value!=null)&&(value.Length!=1000)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+1000)+" was expected for variable \'time_passed\'");
				}
				this.Time_passed = value;
				this.numberOfIterationsDone = 0;
				this.Changed_PlayerInTeam_time_passed_isDone = false;
				this.Changed_numberOfIterationsDecreased_PlayerIndex_PlayerInTeam_vint__212_Init_time_passed_vdouble__8005_isInitialised = false;
				this.Changed_numberOfIterations_PlayerIndex_PlayerInTeam_time_passed_vdouble__800_vdouble__801_vint__212_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'vdouble__800'</summary>
		public double[] vdouble__800
		{
			get {
				return this.Vdouble__800;
			}
			set {
				if ((value!=null)&&(value.Length!=6382)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+6382)+" was expected for variable \'vdouble__800\'");
				}
				this.Vdouble__800 = value;
				this.numberOfIterationsDone = 0;
				this.Changed_vdouble__800_isDone = false;
				this.Changed_numberOfIterationsDecreased_PlayerIndex_PlayerInTeam_vint__212_Init_time_passed_vdouble__8005_isInitialised = false;
				this.Changed_numberOfIterations_PlayerIndex_PlayerInTeam_time_passed_vdouble__800_vdouble__801_vint__212_isDone = false;
				this.Changed_numberOfIterationsDecreased_Init_matchTime_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isInitialised = false;
				this.Changed_matchTime_numberOfIterations_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'vdouble__801'</summary>
		public double[] vdouble__801
		{
			get {
				return this.Vdouble__801;
			}
			set {
				if ((value!=null)&&(value.Length!=6382)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+6382)+" was expected for variable \'vdouble__801\'");
				}
				this.Vdouble__801 = value;
				this.numberOfIterationsDone = 0;
				this.Changed_vdouble__801_isDone = false;
				this.Changed_numberOfIterationsDecreased_PlayerIndex_PlayerInTeam_vint__212_Init_time_passed_vdouble__8005_isInitialised = false;
				this.Changed_numberOfIterations_PlayerIndex_PlayerInTeam_time_passed_vdouble__800_vdouble__801_vint__212_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'vint__212'</summary>
		public int[] vint__212
		{
			get {
				return this.Vint__212;
			}
			set {
				if ((value!=null)&&(value.Length!=6382)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+6382)+" was expected for variable \'vint__212\'");
				}
				this.Vint__212 = value;
				this.numberOfIterationsDone = 0;
				this.Changed_vint__212_isDone = false;
				this.Changed_PlayerIndex_PlayerInTeam_vint__212_isDone = false;
				this.Changed_numberOfIterationsDecreased_PlayerIndex_PlayerInTeam_vint__212_Init_time_passed_vdouble__8005_isDone = false;
				this.Changed_numberOfIterations_PlayerIndex_PlayerInTeam_time_passed_vdouble__800_vdouble__801_vint__212_isDone = false;
			}
		}

		#endregion

		#region Methods
		/// <summary>Computations that depend on the observed value of matchTime</summary>
		private void Changed_matchTime()
		{
			if (this.Changed_matchTime_isDone) {
				return ;
			}
			// Create array for 'matchTime_marginal' Forwards messages.
			this.matchTime_marginal_F = new DistributionStructArray<Gaussian,double>(1000);
			for(int nMatches = 0; nMatches<1000; nMatches++) {
				this.matchTime_marginal_F[nMatches] = Gaussian.Uniform();
			}
			// Message to 'matchTime_marginal' from DerivedVariable factor
			this.matchTime_marginal_F = DerivedVariableOp.MarginalAverageConditional<DistributionStructArray<Gaussian,double>,double[]>(this.MatchTime, this.matchTime_marginal_F);
			this.Changed_matchTime_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of matchTime and numberOfIterations and PlayerIndex and PlayerInTeam and playerTime and vdouble__800</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		private void Changed_matchTime_numberOfIterations_PlayerIndex_PlayerInTeam_playerTime_vdouble__800(int numberOfIterations)
		{
			if (this.Changed_matchTime_numberOfIterations_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isDone) {
				return ;
			}
			DistributionStructArray<Gaussian,double> vdouble__802_F;
			// Create array for 'vdouble__802' Forwards messages.
			vdouble__802_F = new DistributionStructArray<Gaussian,double>(1000);
			for(int nMatches = 0; nMatches<1000; nMatches++) {
				vdouble__802_F[nMatches] = Gaussian.Uniform();
			}
			// Create array for replicates of 'vdouble____232_F'
			DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>[] vdouble____232_F = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>[1000];
			// Create array for replicates of 'vdouble2709_F'
			Gaussian[][][] vdouble2709_F = new Gaussian[1000][][];
			// Create array for replicates of 'vdouble2713_F'
			Gaussian[] vdouble2713_F = new Gaussian[1000];
			// Create array for replicates of 'vdouble2714_F'
			Gaussian[] vdouble2714_F = new Gaussian[1000];
			// Create array for replicates of 'vdouble2707_F'
			Gaussian[][][] vdouble2707_F = new Gaussian[1000][][];
			for(int nMatches = 0; nMatches<1000; nMatches++) {
				// Create array for 'vdouble____232' Forwards messages.
				vdouble____232_F[nMatches] = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(2);
				// Create array for replicates of 'vdouble2707_F'
				vdouble2707_F[nMatches] = new Gaussian[2][];
				// Create array for replicates of 'vdouble2709_F'
				vdouble2709_F[nMatches] = new Gaussian[2][];
				for(int nTeamsPerMatch = 0; nTeamsPerMatch<2; nTeamsPerMatch++) {
					// Create array for 'vdouble____232' Forwards messages.
					vdouble____232_F[nMatches][nTeamsPerMatch] = new DistributionStructArray<Gaussian,double>(this.playerInTeam[nMatches][nTeamsPerMatch]);
					// Create array for replicates of 'vdouble2707_F'
					vdouble2707_F[nMatches][nTeamsPerMatch] = new Gaussian[this.playerInTeam[nMatches][nTeamsPerMatch]];
					// Create array for replicates of 'vdouble2709_F'
					vdouble2709_F[nMatches][nTeamsPerMatch] = new Gaussian[this.playerInTeam[nMatches][nTeamsPerMatch]];
					for(int nPlayersMinusPerTeam = 0; nPlayersMinusPerTeam<this.playerInTeam[nMatches][nTeamsPerMatch]; nPlayersMinusPerTeam++) {
						vdouble____232_F[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam] = Gaussian.Uniform();
						vdouble2707_F[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam] = Gaussian.Uniform();
						// Message to 'vdouble2707' from Gaussian factor
						vdouble2707_F[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam] = GaussianOpBase.SampleAverageConditional(this.Vdouble__800[this.playerIndex[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam]], 1.0);
						vdouble2709_F[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam] = Gaussian.Uniform();
						// Message to 'vdouble2709' from Product factor
						vdouble2709_F[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam] = GaussianProductOpBase.ProductAverageConditional(vdouble2707_F[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam], this.PlayerTime[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam]);
						// Message to 'vdouble____232' from Ratio factor
						vdouble____232_F[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam] = RatioGaussianOp.RatioAverageConditional(vdouble2709_F[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam], this.MatchTime[nMatches]);
					}
				}
				vdouble2713_F[nMatches] = Gaussian.Uniform();
				// Message to 'vdouble2713' from Sum factor
				vdouble2713_F[nMatches] = FastSumOp.SumAverageConditional(vdouble____232_F[nMatches][0]);
				vdouble2714_F[nMatches] = Gaussian.Uniform();
				// Message to 'vdouble2714' from Sum factor
				vdouble2714_F[nMatches] = FastSumOp.SumAverageConditional(vdouble____232_F[nMatches][1]);
				// Message to 'vdouble__802' from Difference factor
				vdouble__802_F[nMatches] = Tracing.FireEvent<Gaussian>(DoublePlusOp.AAverageConditional(vdouble2713_F[nMatches], vdouble2714_F[nMatches]), string.Format("vdouble__802_F[{0}]", new object[1] {nMatches}), this.OnMessageUpdated, false);
			}
			Gaussian vdouble__802_use_B_reduced;
			vdouble__802_use_B_reduced = Gaussian.Uniform();
			for(int iteration = this.numberOfIterationsDone; iteration<numberOfIterations; iteration++) {
				for(int nMatches = 0; nMatches<1000; nMatches++) {
					this.vdouble__802_use_B_nMatches__buffer[nMatches] = VariablePointOp_Rprop.Buffer(vdouble__802_use_B_reduced, vdouble__802_F[nMatches], this.vdouble__802_marginal_F[nMatches], this.vdouble__802_use_B_nMatches__buffer[nMatches]);
					// Message to 'vdouble__802_marginal' from VariablePoint factor
					this.vdouble__802_marginal_F[nMatches] = Tracing.FireEvent<Gaussian>(VariablePointOp_Rprop.MarginalAverageConditional(vdouble__802_use_B_reduced, vdouble__802_F[nMatches], this.vdouble__802_use_B_nMatches__buffer[nMatches], this.vdouble__802_marginal_F[nMatches]), string.Format("vdouble__802_marginal_F[{0}]", new object[1] {nMatches}), this.OnMessageUpdated, false);
				}
				this.OnProgressChanged(new ProgressChangedEventArgs(iteration));
			}
			this.Changed_matchTime_numberOfIterations_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfIterations and PlayerIndex and PlayerInTeam and time_passed and vdouble__800 and vdouble__801 and vint__212</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		private void Changed_numberOfIterations_PlayerIndex_PlayerInTeam_time_passed_vdouble__800_vdouble__801_vint__212(int numberOfIterations)
		{
			if (this.Changed_numberOfIterations_PlayerIndex_PlayerInTeam_time_passed_vdouble__800_vdouble__801_vint__212_isDone) {
				return ;
			}
			DistributionStructArray<Gaussian,double> vdouble__809_F;
			// Create array for 'vdouble__809' Forwards messages.
			vdouble__809_F = new DistributionStructArray<Gaussian,double>(6382);
			// Create array for 'vdouble__809_marginal' Forwards messages.
			this.vdouble__809_marginal_F = new DistributionStructArray<Gaussian,double>(6382);
			DistributionStructArray<Gaussian,double> vdouble__809_use_B;
			// Create array for 'vdouble__809_use' Backwards messages.
			vdouble__809_use_B = new DistributionStructArray<Gaussian,double>(6382);
			for(int nPlayers = 0; nPlayers<6382; nPlayers++) {
				vdouble__809_use_B[nPlayers] = Gaussian.Uniform();
			}
			DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]> vdouble__809_itemPlayerIndex_nMatches__nTeamsPerMatch__nPlayersMinusPerTeam__B;
			// Create array for 'vdouble__809_itemPlayerIndex_nMatches__nTeamsPerMatch__nPlayersMinusPerTeam_' Backwards messages.
			vdouble__809_itemPlayerIndex_nMatches__nTeamsPerMatch__nPlayersMinusPerTeam__B = new DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]>(1000);
			// Create array for replicates of 'vdouble2727'
			double[][][] vdouble2727 = new double[1000][][];
			// Create array for replicates of 'vdouble2725_B'
			Gaussian[][][] vdouble2725_B = new Gaussian[1000][][];
			for(int nMatches = 0; nMatches<1000; nMatches++) {
				// Create array for replicates of 'vdouble2727'
				vdouble2727[nMatches] = new double[2][];
				// Create array for replicates of 'vdouble2725_B'
				vdouble2725_B[nMatches] = new Gaussian[2][];
				for(int nTeamsPerMatch = 0; nTeamsPerMatch<2; nTeamsPerMatch++) {
					// Create array for replicates of 'vdouble2727'
					vdouble2727[nMatches][nTeamsPerMatch] = new double[this.playerInTeam[nMatches][nTeamsPerMatch]];
					// Create array for replicates of 'vdouble2725_B'
					vdouble2725_B[nMatches][nTeamsPerMatch] = new Gaussian[this.playerInTeam[nMatches][nTeamsPerMatch]];
					for(int nPlayersMinusPerTeam = 0; nPlayersMinusPerTeam<this.playerInTeam[nMatches][nTeamsPerMatch]; nPlayersMinusPerTeam++) {
						if (this.Vint__212[this.playerIndex[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam]]==1) {
							vdouble2727[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam] = Factor.Product(1.6484251002148446E-15, this.Time_passed[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam]);
							vdouble2725_B[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam] = Gaussian.Uniform();
							// Message to 'vdouble2725' from Gaussian factor
							vdouble2725_B[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam] = GaussianOpBase.MeanAverageConditional(this.Vdouble__800[this.playerIndex[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam]], vdouble2727[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam]);
						}
					}
				}
			}
			for(int iteration = this.numberOfIterationsDone; iteration<numberOfIterations; iteration++) {
				for(int nMatches = 0; nMatches<1000; nMatches++) {
					for(int nTeamsPerMatch = 0; nTeamsPerMatch<2; nTeamsPerMatch++) {
						for(int nPlayersMinusPerTeam = 0; nPlayersMinusPerTeam<this.playerInTeam[nMatches][nTeamsPerMatch]; nPlayersMinusPerTeam++) {
							if (this.Vint__212[this.playerIndex[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam]]==1) {
								// Message to 'vdouble__809_PlayerIndex_nMatches_nTeamsPerMatch_nPlayersMinusPerTeam_1_' from Backward factor
								this.vdouble__809_PlayerIndex_nMatches_nTeamsPerMatch_nPlayersMinusPerTeam_1__B[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam] = DampBackwardOp.ValueAverageConditional<Gaussian>(vdouble2725_B[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam], 0.5, this.vdouble__809_PlayerIndex_nMatches_nTeamsPerMatch_nPlayersMinusPerTeam_1__B[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam]);
							}
						}
					}
				}
				this.OnProgressChanged(new ProgressChangedEventArgs(iteration));
			}
			for(int nMatches = 0; nMatches<1000; nMatches++) {
				// Create array for 'vdouble__809_itemPlayerIndex_nMatches__nTeamsPerMatch__nPlayersMinusPerTeam_' Backwards messages.
				vdouble__809_itemPlayerIndex_nMatches__nTeamsPerMatch__nPlayersMinusPerTeam__B[nMatches] = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(2);
				for(int nTeamsPerMatch = 0; nTeamsPerMatch<2; nTeamsPerMatch++) {
					// Create array for 'vdouble__809_itemPlayerIndex_nMatches__nTeamsPerMatch__nPlayersMinusPerTeam_' Backwards messages.
					vdouble__809_itemPlayerIndex_nMatches__nTeamsPerMatch__nPlayersMinusPerTeam__B[nMatches][nTeamsPerMatch] = new DistributionStructArray<Gaussian,double>(this.playerInTeam[nMatches][nTeamsPerMatch]);
					for(int nPlayersMinusPerTeam = 0; nPlayersMinusPerTeam<this.playerInTeam[nMatches][nTeamsPerMatch]; nPlayersMinusPerTeam++) {
						vdouble__809_itemPlayerIndex_nMatches__nTeamsPerMatch__nPlayersMinusPerTeam__B[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam] = Gaussian.Uniform();
						if (this.Vint__212[this.playerIndex[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam]]==1) {
							// Message to 'vdouble__809_itemPlayerIndex_nMatches__nTeamsPerMatch__nPlayersMinusPerTeam_' from Copy factor
							vdouble__809_itemPlayerIndex_nMatches__nTeamsPerMatch__nPlayersMinusPerTeam__B[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam] = ArrayHelper.SetTo<Gaussian>(vdouble__809_itemPlayerIndex_nMatches__nTeamsPerMatch__nPlayersMinusPerTeam__B[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam], this.vdouble__809_PlayerIndex_nMatches_nTeamsPerMatch_nPlayersMinusPerTeam_1__B[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam]);
						}
					}
				}
			}
			// Message to 'vdouble__809_use' from GetDeepJaggedItems factor
			vdouble__809_use_B = GetDeepJaggedItemsOp<double>.ArrayAverageConditional<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,DistributionStructArray<Gaussian,double>,Gaussian,DistributionStructArray<Gaussian,double>>(vdouble__809_itemPlayerIndex_nMatches__nTeamsPerMatch__nPlayersMinusPerTeam__B, this.playerIndex, vdouble__809_use_B);
			for(int nPlayers = 0; nPlayers<6382; nPlayers++) {
				vdouble__809_F[nPlayers] = Gaussian.Uniform();
				this.vdouble__809_marginal_F[nPlayers] = Gaussian.Uniform();
				// Message to 'vdouble__809' from Gaussian factor
				vdouble__809_F[nPlayers] = GaussianOpBase.SampleAverageConditional(this.Vdouble__800[nPlayers], this.Vdouble__801[nPlayers]);
				// Message to 'vdouble__809_marginal' from Variable factor
				this.vdouble__809_marginal_F[nPlayers] = VariableOp.MarginalAverageConditional<Gaussian>(vdouble__809_use_B[nPlayers], vdouble__809_F[nPlayers], this.vdouble__809_marginal_F[nPlayers]);
			}
			this.Changed_numberOfIterations_PlayerIndex_PlayerInTeam_time_passed_vdouble__800_vdouble__801_vint__212_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfIterationsDecreased and must reset on changes to matchTime and PlayerIndex and PlayerInTeam and playerTime and vdouble__800</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_numberOfIterationsDecreased_Init_matchTime_PlayerIndex_PlayerInTeam_playerTime_vdouble__800(bool initialise)
		{
			if (this.Changed_numberOfIterationsDecreased_Init_matchTime_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isDone&&((!initialise)||this.Changed_numberOfIterationsDecreased_Init_matchTime_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isInitialised)) {
				return ;
			}
			for(int nMatches = 0; nMatches<1000; nMatches++) {
				this.vdouble__802_marginal_F[nMatches] = Gaussian.Uniform();
				this.vdouble__802_use_B_nMatches__buffer[nMatches] = VariablePointOp_Rprop.BufferInit();
			}
			this.Changed_numberOfIterationsDecreased_Init_matchTime_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isDone = true;
			this.Changed_numberOfIterationsDecreased_Init_matchTime_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfIterationsDecreased and PlayerIndex and PlayerInTeam and vint__212 and must reset on changes to time_passed and vdouble__800 and vdouble__801</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_numberOfIterationsDecreased_PlayerIndex_PlayerInTeam_vint__212_Init_time_passed_vdouble__8005(bool initialise)
		{
			if (this.Changed_numberOfIterationsDecreased_PlayerIndex_PlayerInTeam_vint__212_Init_time_passed_vdouble__8005_isDone&&((!initialise)||this.Changed_numberOfIterationsDecreased_PlayerIndex_PlayerInTeam_vint__212_Init_time_passed_vdouble__8005_isInitialised)) {
				return ;
			}
			for(int nMatches = 0; nMatches<1000; nMatches++) {
				for(int nTeamsPerMatch = 0; nTeamsPerMatch<2; nTeamsPerMatch++) {
					for(int nPlayersMinusPerTeam = 0; nPlayersMinusPerTeam<this.playerInTeam[nMatches][nTeamsPerMatch]; nPlayersMinusPerTeam++) {
						if (this.Vint__212[this.playerIndex[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam]]==1) {
							this.vdouble__809_PlayerIndex_nMatches_nTeamsPerMatch_nPlayersMinusPerTeam_1__B[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam] = Gaussian.Uniform();
						}
					}
				}
			}
			this.Changed_numberOfIterationsDecreased_PlayerIndex_PlayerInTeam_vint__212_Init_time_passed_vdouble__8005_isDone = true;
			this.Changed_numberOfIterationsDecreased_PlayerIndex_PlayerInTeam_vint__212_Init_time_passed_vdouble__8005_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of PlayerIndex</summary>
		private void Changed_PlayerIndex()
		{
			if (this.Changed_PlayerIndex_isDone) {
				return ;
			}
			// Create array for 'PlayerIndex_marginal' Forwards messages.
			this.PlayerIndex_marginal_F = new PointMass<int[][][]>(this.playerIndex);
			// Message to 'PlayerIndex_marginal' from DerivedVariable factor
			this.PlayerIndex_marginal_F = DerivedVariableOp.MarginalAverageConditional<PointMass<int[][][]>,int[][][]>(this.playerIndex, this.PlayerIndex_marginal_F);
			this.Changed_PlayerIndex_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of PlayerIndex and PlayerInTeam and vint__212</summary>
		private void Changed_PlayerIndex_PlayerInTeam_vint__212()
		{
			if (this.Changed_PlayerIndex_PlayerInTeam_vint__212_isDone) {
				return ;
			}
			for(int nMatches = 0; nMatches<1000; nMatches++) {
				for(int nTeamsPerMatch = 0; nTeamsPerMatch<2; nTeamsPerMatch++) {
					// Create array for replicates of 'vdouble__809_PlayerIndex_nMatches_nTeamsPerMatch_nPlayersMinusPerTeam_1__B'
					this.vdouble__809_PlayerIndex_nMatches_nTeamsPerMatch_nPlayersMinusPerTeam_1__B[nMatches][nTeamsPerMatch] = new Gaussian[this.playerInTeam[nMatches][nTeamsPerMatch]];
				}
			}
			this.Changed_PlayerIndex_PlayerInTeam_vint__212_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of PlayerInTeam</summary>
		private void Changed_PlayerInTeam()
		{
			if (this.Changed_PlayerInTeam_isDone) {
				return ;
			}
			// Create array for 'PlayerInTeam_marginal' Forwards messages.
			this.PlayerInTeam_marginal_F = new PointMass<int[][]>(this.playerInTeam);
			// Message to 'PlayerInTeam_marginal' from DerivedVariable factor
			this.PlayerInTeam_marginal_F = DerivedVariableOp.MarginalAverageConditional<PointMass<int[][]>,int[][]>(this.playerInTeam, this.PlayerInTeam_marginal_F);
			this.Changed_PlayerInTeam_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of PlayerInTeam and playerTime</summary>
		private void Changed_PlayerInTeam_playerTime()
		{
			if (this.Changed_PlayerInTeam_playerTime_isDone) {
				return ;
			}
			// Create array for 'playerTime_marginal' Forwards messages.
			this.playerTime_marginal_F = new DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]>(1000);
			for(int nMatches = 0; nMatches<1000; nMatches++) {
				// Create array for 'playerTime_marginal' Forwards messages.
				this.playerTime_marginal_F[nMatches] = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(2);
				for(int nTeamsPerMatch = 0; nTeamsPerMatch<2; nTeamsPerMatch++) {
					// Create array for 'playerTime_marginal' Forwards messages.
					this.playerTime_marginal_F[nMatches][nTeamsPerMatch] = new DistributionStructArray<Gaussian,double>(this.playerInTeam[nMatches][nTeamsPerMatch]);
					for(int nPlayersMinusPerTeam = 0; nPlayersMinusPerTeam<this.playerInTeam[nMatches][nTeamsPerMatch]; nPlayersMinusPerTeam++) {
						this.playerTime_marginal_F[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam] = Gaussian.Uniform();
					}
				}
			}
			// Message to 'playerTime_marginal' from DerivedVariable factor
			this.playerTime_marginal_F = DerivedVariableOp.MarginalAverageConditional<DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]>,double[][][]>(this.PlayerTime, this.playerTime_marginal_F);
			this.Changed_PlayerInTeam_playerTime_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of PlayerInTeam and time_passed</summary>
		private void Changed_PlayerInTeam_time_passed()
		{
			if (this.Changed_PlayerInTeam_time_passed_isDone) {
				return ;
			}
			// Create array for 'time_passed_marginal' Forwards messages.
			this.time_passed_marginal_F = new DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]>(1000);
			for(int nMatches = 0; nMatches<1000; nMatches++) {
				// Create array for 'time_passed_marginal' Forwards messages.
				this.time_passed_marginal_F[nMatches] = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(2);
				for(int nTeamsPerMatch = 0; nTeamsPerMatch<2; nTeamsPerMatch++) {
					// Create array for 'time_passed_marginal' Forwards messages.
					this.time_passed_marginal_F[nMatches][nTeamsPerMatch] = new DistributionStructArray<Gaussian,double>(this.playerInTeam[nMatches][nTeamsPerMatch]);
					for(int nPlayersMinusPerTeam = 0; nPlayersMinusPerTeam<this.playerInTeam[nMatches][nTeamsPerMatch]; nPlayersMinusPerTeam++) {
						this.time_passed_marginal_F[nMatches][nTeamsPerMatch][nPlayersMinusPerTeam] = Gaussian.Uniform();
					}
				}
			}
			// Message to 'time_passed_marginal' from DerivedVariable factor
			this.time_passed_marginal_F = DerivedVariableOp.MarginalAverageConditional<DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]>,double[][][]>(this.Time_passed, this.time_passed_marginal_F);
			this.Changed_PlayerInTeam_time_passed_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of vdouble__800</summary>
		private void Changed_vdouble__800()
		{
			if (this.Changed_vdouble__800_isDone) {
				return ;
			}
			// Create array for 'vdouble__800_marginal' Forwards messages.
			this.vdouble__800_marginal_F = new DistributionStructArray<Gaussian,double>(6382);
			for(int nPlayers = 0; nPlayers<6382; nPlayers++) {
				this.vdouble__800_marginal_F[nPlayers] = Gaussian.Uniform();
			}
			// Message to 'vdouble__800_marginal' from DerivedVariable factor
			this.vdouble__800_marginal_F = DerivedVariableOp.MarginalAverageConditional<DistributionStructArray<Gaussian,double>,double[]>(this.Vdouble__800, this.vdouble__800_marginal_F);
			this.Changed_vdouble__800_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of vdouble__801</summary>
		private void Changed_vdouble__801()
		{
			if (this.Changed_vdouble__801_isDone) {
				return ;
			}
			// Create array for 'vdouble__801_marginal' Forwards messages.
			this.vdouble__801_marginal_F = new DistributionStructArray<Gaussian,double>(6382);
			for(int nPlayers = 0; nPlayers<6382; nPlayers++) {
				this.vdouble__801_marginal_F[nPlayers] = Gaussian.Uniform();
			}
			// Message to 'vdouble__801_marginal' from DerivedVariable factor
			this.vdouble__801_marginal_F = DerivedVariableOp.MarginalAverageConditional<DistributionStructArray<Gaussian,double>,double[]>(this.Vdouble__801, this.vdouble__801_marginal_F);
			this.Changed_vdouble__801_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of vint__212</summary>
		private void Changed_vint__212()
		{
			if (this.Changed_vint__212_isDone) {
				return ;
			}
			// Create array for 'vint__212_marginal' Forwards messages.
			this.vint__212_marginal_F = new PointMass<int[]>(this.Vint__212);
			// Message to 'vint__212_marginal' from DerivedVariable factor
			this.vint__212_marginal_F = DerivedVariableOp.MarginalAverageConditional<PointMass<int[]>,int[]>(this.Vint__212, this.vint__212_marginal_F);
			this.Changed_vint__212_isDone = true;
		}

		/// <summary>Computations that do not depend on observed values</summary>
		private void Constant()
		{
			if (this.Constant_isDone) {
				return ;
			}
			// Create array for 'vdouble__802_marginal' Forwards messages.
			this.vdouble__802_marginal_F = new DistributionStructArray<Gaussian,double>(1000);
			// Create array for replicates of 'vdouble__802_use_B_nMatches__buffer'
			this.vdouble__802_use_B_nMatches__buffer = new RpropBufferData[1000];
			// Create array for replicates of 'vdouble__809_PlayerIndex_nMatches_nTeamsPerMatch_nPlayersMinusPerTeam_1__B'
			this.vdouble__809_PlayerIndex_nMatches_nTeamsPerMatch_nPlayersMinusPerTeam_1__B = new Gaussian[1000][][];
			for(int nMatches = 0; nMatches<1000; nMatches++) {
				// Create array for replicates of 'vdouble__809_PlayerIndex_nMatches_nTeamsPerMatch_nPlayersMinusPerTeam_1__B'
				this.vdouble__809_PlayerIndex_nMatches_nTeamsPerMatch_nPlayersMinusPerTeam_1__B[nMatches] = new Gaussian[2][];
			}
			this.Constant_isDone = true;
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			if (numberOfIterations!=this.numberOfIterationsDone) {
				if (numberOfIterations<this.numberOfIterationsDone) {
					this.numberOfIterationsDone = 0;
					this.Changed_numberOfIterationsDecreased_PlayerIndex_PlayerInTeam_vint__212_Init_time_passed_vdouble__8005_isDone = false;
					this.Changed_numberOfIterationsDecreased_Init_matchTime_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isDone = false;
				}
				this.Changed_numberOfIterations_PlayerIndex_PlayerInTeam_time_passed_vdouble__800_vdouble__801_vint__212_isDone = false;
				this.Changed_matchTime_numberOfIterations_PlayerIndex_PlayerInTeam_playerTime_vdouble__800_isDone = false;
			}
			this.Changed_vdouble__801();
			this.Changed_vdouble__800();
			this.Changed_vint__212();
			this.Changed_PlayerInTeam_time_passed();
			this.Changed_PlayerInTeam_playerTime();
			this.Changed_matchTime();
			this.Changed_PlayerIndex();
			this.Changed_PlayerInTeam();
			this.Constant();
			this.Changed_PlayerIndex_PlayerInTeam_vint__212();
			this.Changed_numberOfIterationsDecreased_PlayerIndex_PlayerInTeam_vint__212_Init_time_passed_vdouble__8005(initialise);
			this.Changed_numberOfIterations_PlayerIndex_PlayerInTeam_time_passed_vdouble__800_vdouble__801_vint__212(numberOfIterations);
			this.Changed_numberOfIterationsDecreased_Init_matchTime_PlayerIndex_PlayerInTeam_playerTime_vdouble__800(initialise);
			this.Changed_matchTime_numberOfIterations_PlayerIndex_PlayerInTeam_playerTime_vdouble__800(numberOfIterations);
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			if (variableName=="PlayerInTeam") {
				return this.PlayerInTeam;
			}
			if (variableName=="PlayerIndex") {
				return this.PlayerIndex;
			}
			if (variableName=="matchTime") {
				return this.matchTime;
			}
			if (variableName=="playerTime") {
				return this.playerTime;
			}
			if (variableName=="time_passed") {
				return this.time_passed;
			}
			if (variableName=="vint__212") {
				return this.vint__212;
			}
			if (variableName=="vdouble__800") {
				return this.vdouble__800;
			}
			if (variableName=="vdouble__801") {
				return this.vdouble__801;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="vdouble__801") {
				return this.Vdouble__801Marginal();
			}
			if (variableName=="vdouble__800") {
				return this.Vdouble__800Marginal();
			}
			if (variableName=="vint__212") {
				return this.Vint__212Marginal();
			}
			if (variableName=="time_passed") {
				return this.Time_passedMarginal();
			}
			if (variableName=="playerTime") {
				return this.PlayerTimeMarginal();
			}
			if (variableName=="matchTime") {
				return this.MatchTimeMarginal();
			}
			if (variableName=="PlayerIndex") {
				return this.PlayerIndexMarginal();
			}
			if (variableName=="PlayerInTeam") {
				return this.PlayerInTeamMarginal();
			}
			if (variableName=="vdouble__809") {
				return this.Vdouble__809Marginal();
			}
			if (variableName=="vdouble__802") {
				return this.Vdouble__802Marginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		/// <summary>
		/// Returns the marginal distribution for 'matchTime' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray<Gaussian,double> MatchTimeMarginal()
		{
			return this.matchTime_marginal_F;
		}

		private void OnMessageUpdated(MessageUpdatedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<MessageUpdatedEventArgs> handler = this.MessageUpdated;
			if (handler!=null) {
				handler(this, e);
			}
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>
		/// Returns the marginal distribution for 'PlayerIndex' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public PointMass<int[][][]> PlayerIndexMarginal()
		{
			return this.PlayerIndex_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'PlayerInTeam' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public PointMass<int[][]> PlayerInTeamMarginal()
		{
			return this.PlayerInTeam_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'playerTime' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]> PlayerTimeMarginal()
		{
			return this.playerTime_marginal_F;
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			if (variableName=="PlayerInTeam") {
				this.PlayerInTeam = (int[][])value;
				return ;
			}
			if (variableName=="PlayerIndex") {
				this.PlayerIndex = (int[][][])value;
				return ;
			}
			if (variableName=="matchTime") {
				this.matchTime = (double[])value;
				return ;
			}
			if (variableName=="playerTime") {
				this.playerTime = (double[][][])value;
				return ;
			}
			if (variableName=="time_passed") {
				this.time_passed = (double[][][])value;
				return ;
			}
			if (variableName=="vint__212") {
				this.vint__212 = (int[])value;
				return ;
			}
			if (variableName=="vdouble__800") {
				this.vdouble__800 = (double[])value;
				return ;
			}
			if (variableName=="vdouble__801") {
				this.vdouble__801 = (double[])value;
				return ;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>
		/// Returns the marginal distribution for 'time_passed' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]> Time_passedMarginal()
		{
			return this.time_passed_marginal_F;
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(checked(this.numberOfIterationsDone+additionalIterations), false);
		}

		/// <summary>
		/// Returns the marginal distribution for 'vdouble__800' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray<Gaussian,double> Vdouble__800Marginal()
		{
			return this.vdouble__800_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vdouble__801' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray<Gaussian,double> Vdouble__801Marginal()
		{
			return this.vdouble__801_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vdouble__802' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray<Gaussian,double> Vdouble__802Marginal()
		{
			return ArrayHelper.MakeCopy<DistributionStructArray<Gaussian,double>>(this.vdouble__802_marginal_F);
		}

		/// <summary>
		/// Returns the marginal distribution for 'vdouble__809' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray<Gaussian,double> Vdouble__809Marginal()
		{
			return this.vdouble__809_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vint__212' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public PointMass<int[]> Vint__212Marginal()
		{
			return this.vint__212_marginal_F;
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		/// <summary>Event that is fired when a message that is being monitored is updated.</summary>
		public event EventHandler<MessageUpdatedEventArgs> MessageUpdated;
		#endregion

	}

}
